/* GENERATED by tools/gen_c_schema.py from ../schema.json. DO NOT EDIT. */
/* Source schema version: 1.0.0 */
#ifndef CVFR_SCHEMA_H
#define CVFR_SCHEMA_H

#include <stdbool.h>

#define CVFR_PORT             2020
#define CVFR_SCHEMA_VERSION   "1.0.0"

#define CVFR_FIELD_LATITUDE       "latitude"
#define CVFR_FORMAT_LATITUDE      "%.6f"
#define CVFR_FALLBACK_LATITUDE    32.0055
#define CVFR_FIELD_LONGITUDE      "longitude"
#define CVFR_FORMAT_LONGITUDE     "%.6f"
#define CVFR_FALLBACK_LONGITUDE   34.8854
#define CVFR_FIELD_ALTITUDE       "altitude"
#define CVFR_FORMAT_ALTITUDE      "%d"
#define CVFR_FALLBACK_ALTITUDE    135
#define CVFR_FIELD_HEADING        "heading"
#define CVFR_FORMAT_HEADING       "%.1f"
#define CVFR_FALLBACK_HEADING     0.0
#define CVFR_FIELD_VARIATION      "variation"
#define CVFR_FORMAT_VARIATION     "%.1f"
#define CVFR_FALLBACK_VARIATION   4.7
#define CVFR_FIELD_PITCH          "pitch"
#define CVFR_FORMAT_PITCH         "%.2f"
#define CVFR_FALLBACK_PITCH       0.0
#define CVFR_FIELD_ROLL           "roll"
#define CVFR_FORMAT_ROLL          "%.2f"
#define CVFR_FALLBACK_ROLL        0.0
#define CVFR_FIELD_IAS            "ias"
#define CVFR_FORMAT_IAS           "%.1f"
#define CVFR_FALLBACK_IAS         0.0
#define CVFR_FIELD_VSI            "vsi"
#define CVFR_FORMAT_VSI           "%d"
#define CVFR_FALLBACK_VSI         0
#define CVFR_FIELD_WIND_DIR       "wind_dir"
#define CVFR_FORMAT_WIND_DIR      "%.0f"
#define CVFR_FALLBACK_WIND_DIR    0.0
#define CVFR_FIELD_WIND_SPEED     "wind_speed"
#define CVFR_FORMAT_WIND_SPEED    "%.1f"
#define CVFR_FALLBACK_WIND_SPEED  0.0
#define CVFR_FIELD_QNH            "qnh"
#define CVFR_FORMAT_QNH           "%.2f"
#define CVFR_FALLBACK_QNH         29.92
#define CVFR_FIELD_SIM_READY      "sim_ready"
#define CVFR_FORMAT_SIM_READY     "%s"
#define CVFR_FALLBACK_SIM_READY   false

/* JSON body printf format - one snprintf, canonical field order. */
#define CVFR_JSON_TEMPLATE    "{\"latitude\":%.6f,\"longitude\":%.6f,\"altitude\":%d,\"heading\":%.1f,\"variation\":%.1f,\"pitch\":%.2f,\"roll\":%.2f,\"ias\":%.1f,\"vsi\":%d,\"wind_dir\":%.0f,\"wind_speed\":%.1f,\"qnh\":%.2f,\"sim_ready\":%s}"

#endif /* CVFR_SCHEMA_H */
