#!/usr/bin/env python3
"""
Generate c/schema.h from schema.json.

Invoked from CMake as a custom_command before compiling plugin.c, so the
generated header is always in sync with the canonical schema. The
generated file is .gitignored; rebuild produces it from scratch.

What's emitted:
  - CVFR_FIELD_<NAME>          string-literal field name (#define)
  - CVFR_FORMAT_<NAME>         printf format string for the field's value
  - CVFR_FALLBACK_<NAME>       LLBG fallback constant
  - CVFR_JSON_TEMPLATE         a single printf format string for the
                                whole JSON body, in canonical field order
  - CVFR_PORT                  HTTP port from schema.json
  - CVFR_SCHEMA_VERSION        string

The plugin's format_json() then becomes a single snprintf using
CVFR_JSON_TEMPLATE plus the per-field value expressions, with no
hand-maintained field-name string literals.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import dedent


def c_str(s: str) -> str:
    """Quote a Python string for use as a C string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fallback_literal(field: dict) -> str:
    """Render a JSON fallback value as a C literal."""
    fb = field["fallback"]
    if field["type"] == "bool":
        return "true" if fb else "false"
    if field["type"] == "int":
        return str(int(fb))
    if field["type"] == "double":
        # Always emit with at least one decimal so it's a double literal.
        return repr(float(fb))
    raise ValueError(f"unknown type for {field['name']}: {field['type']}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--schema", required=True, type=Path, help="schema.json")
    p.add_argument("--output", required=True, type=Path, help="generated schema.h")
    args = p.parse_args()

    schema = json.loads(args.schema.read_text())
    fields = schema["fields"]
    port = schema["port"]
    version = schema.get("version", "0.0.0")

    lines: list[str] = []
    lines.append("/* GENERATED by tools/gen_c_schema.py from ../schema.json. DO NOT EDIT. */")
    lines.append("/* Source schema version: " + version + " */")
    lines.append("#ifndef CVFR_SCHEMA_H")
    lines.append("#define CVFR_SCHEMA_H")
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("")
    lines.append(f"#define CVFR_PORT             {port}")
    lines.append(f"#define CVFR_SCHEMA_VERSION   {c_str(version)}")
    lines.append("")

    # Per-field constants: field name (string), format spec, and LLBG fallback.
    for f in fields:
        u = f["name"].upper()
        lines.append(f"#define CVFR_FIELD_{u:<10}     {c_str(f['name'])}")
        lines.append(f"#define CVFR_FORMAT_{u:<10}    {c_str(f['format'])}")
        lines.append(f"#define CVFR_FALLBACK_{u:<10}  {fallback_literal(f)}")
    lines.append("")

    # CVFR_JSON_TEMPLATE: one printf format string covering the whole
    # JSON body. Plugin code becomes a single snprintf with all field
    # values in canonical order. For bool fields we substitute the
    # caller-provided expression as %s ("true"/"false"); plugin.c knows
    # to format bools that way.
    # Build the JSON body in plain Python (no pre-escaping). c_str() below
    # will handle the C-literal escaping. Pre-escaping here causes double
    # escapes in the generated header.
    parts = []
    for i, f in enumerate(fields):
        sep = "" if i == 0 else ","
        parts.append(sep + '"' + f["name"] + '":' + f["format"])
    body = "{" + "".join(parts) + "}"
    lines.append("/* JSON body printf format - one snprintf, canonical field order. */")
    lines.append(f"#define CVFR_JSON_TEMPLATE    {c_str(body)}")
    lines.append("")
    lines.append("#endif /* CVFR_SCHEMA_H */")

    out = "\n".join(lines) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out)
    print(f"gen_c_schema: wrote {args.output} ({len(fields)} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
